-- MySQL Script generated by MySQL Workbench
-- Thu Oct  5 16:22:48 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema datos_regional
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `datos_regional` ;

-- -----------------------------------------------------
-- Schema datos_regional
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `datos_regional` ;
USE `datos_regional` ;

-- -----------------------------------------------------
-- Table `datos_regional`.`datos_personales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datos_regional`.`datos_personales` ;

CREATE TABLE IF NOT EXISTS `datos_regional`.`datos_personales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(125) NOT NULL,
  `apellido` VARCHAR(125) NOT NULL,
  `documento` VARCHAR(45) NOT NULL,
  `telefono` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datos_regional`.`materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datos_regional`.`materias` ;

CREATE TABLE IF NOT EXISTS `datos_regional`.`materias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_materia` VARCHAR(85) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datos_regional`.`calificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datos_regional`.`calificaciones` ;

CREATE TABLE IF NOT EXISTS `datos_regional`.`calificaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_estudiante` INT NOT NULL,
  `id_materia` INT NOT NULL,
  `calificacion` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_materia_idx` (`id_materia` ASC),
  INDEX `id_estudiante_idx` (`id_estudiante` ASC),
  CONSTRAINT `id_materia`
    FOREIGN KEY (`id_materia`)
    REFERENCES `datos_regional`.`materias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_estudiante`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `datos_regional`.`datos_personales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `datos_regional`.`datos_personales` (`nombre`, `apellido`, `documento`, `telefono`) VALUES ('Ivan', 'Mejia', '123', '34567');
INSERT INTO `datos_regional`.`datos_personales` (`nombre`, `apellido`, `documento`, `telefono`) VALUES ('Juan', 'De Montreal', '234', '9876');
INSERT INTO `datos_regional`.`datos_personales` (`nombre`, `apellido`, `documento`, `telefono`) VALUES ('Vicente', 'Fernandez', '345', '9203');
INSERT INTO `datos_regional`.`datos_personales` (`nombre`, `apellido`, `documento`, `telefono`) VALUES ('Laura', 'Pinto', '456', '3458');

INSERT INTO `datos_regional`.`materias` (`nombre_materia`) VALUES ('Sistemas Operativos I');
INSERT INTO `datos_regional`.`materias` (`nombre_materia`) VALUES ('Sistemas Operativos II');
INSERT INTO `datos_regional`.`materias` (`nombre_materia`) VALUES ('Regional I');
INSERT INTO `datos_regional`.`materias` (`nombre_materia`) VALUES ('Regional II');
INSERT INTO `datos_regional`.`materias` (`nombre_materia`) VALUES ('Regional III');

INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (1, 1, 2);
INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (1, 2, 3);
INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (1, 3, 2.5);
INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (1, 4, 4.1);
INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (1, 5, 3.2);

INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (2, 1, 4.2);
INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (2, 2, 2.5);
INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (2, 3, 4);
INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (2, 4, 4.4);
INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (2, 5, 2.8);

INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (3, 1, 3.2);
INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (3, 2, 5);
INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (3, 3, 4.24);
INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (3, 4, 2);
INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (3, 5, 3);

INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (4, 1, 3);
INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (4, 2, 2);
INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (4, 3, 2.2);
INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (4, 4, 5);
INSERT INTO `datos_regional`.`calificaciones` (`id_estudiante`, `id_materia`, `calificacion`) VALUES (4, 5, 3);

